spring.datasource.initialization-mode=always
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.jdbcUrl=jdbc:mysql://localhost:3306/portafolio?createDatabaseIfNotExist=true&allowMultiQueries=true
spring.datasource.username=root
spring.datasource.password=sasa
spring.datasource.hikari.poolName=pool
logging.level.org.springframework.security=DEBUG
spring.profiles.active=desarrollo
